### PR TITLE
Feat/tutorial UI - ui fixes

### LINKED ISSUE #34: tutorial steps

### PR DESCRIPTION
**Pull request by bradleySuira**
#34 
#47 
#48 
#107

### CODE REVIEW

**Comment by cristiam86** [comment]
@bradleySuira this doesn't seem to solve:
- https://github.com/yeagerai/genlayer-simulator/issues/114
- https://github.com/yeagerai/genlayer-simulator/issues/47
- https://github.com/yeagerai/genlayer-simulator/issues/48

Also, when I choose "dark mode" I see the buttons and dr
Screenshot 2024-05-03 at 15 45 38
opdowns like this:

**Comment by bradleySuira** [comment]
@cristiam86 about  tutorial - save the option that will never show again #47, this is by default if you click on skip tutorial, then you will have the option see again the tutorial at the right top corner

also for this one => tutorial - save if the user has completed the tutorial already #48 we save the flag in local Storage

**Review by cristiam86 — APPROVED** [review]
The dark mode still doesn't look as it should.
@MuncleUscles please review the steps of the tutorial. I'll give it a thought as well and see what we can improve.

**Comment by bradleySuira** [comment]
@cristiam86 pushed fixes about dark mode, please your review

**Comment by cristiam86** [comment]
@bradleySuira, I still see the colors wrong
Screenshot 2024-05-10 at 08 29 15

**Comment by cristiam86** [comment]
@bradleySuira most of the issues Edgards put here: https://github.com/yeagerai/genlayer-simulator/issues/112 are not addressed. Please include them here

**Review by cristiam86 — APPROVED** [review]

**Pull request merged**
