### PR TITLE
89 vscode debugger setup

### PR DESCRIPTION
**Pull request by sevenearths**

### CODE REVIEW

**Comment by cristiam86** [comment]
@sevenearths please explain how anyone could test this :)

**Comment by sevenearths** [comment]
> @sevenearths please explain how anyone could test this :)

Yeah sure.
1. Delete all docker containers
2. Delete `genvm` and `rpc` images
3. Do docker-compose up
4. In VSCode on the left hand side click on `Run and Debug`.
5. At the top of the panel in the debug pull down select `Debug All`
6. In the terminal in VSCode go to `Debug`
7. You should see all the debug information here and in the lefthand column
8. Add a breakpoint

**Review by cristiam86 — CHANGES_REQUESTED** [review]
@sevenearths you are missing the new env variables in the sample file:
RPCDEBUGPORT
GENVMDEBUGPORT

**Review by sevenearths — COMMENTED** [review]
RPCDEBUGPORT and GENVMDEBUGPORT are now in .env.example

**Review by cristiam86 — APPROVED** [review]

**Review by cristiam86 — APPROVED** [review]

**Pull request merged**
