### PR TITLE
Add CodeQL scanning

### PR DESCRIPTION
**Pull request by YeagerAI-Bulat**
## What

This PR adds a GitHub Actions workflow to run CodeQL code scanning on the repository.

## Why

CodeQL is a powerful static analysis tool that can help us identify potential security vulnerabilities and code quality issues early in the development process. This proactive approach will help us maintain a more secure and reliable codebase.

## Testing done
Build run: https://github.com/yeagerai/genlayer-simulator/actions/runs/10093701422
- The workflow successfully runs CodeQL analysis on both Python and JS code within the repository.
- No breaking changes were introduced by the addition of this workflow.

### CODE REVIEW

**Review by cristiam86 — COMMENTED** [review]
I think that running this workflow on PR open and on every or update could be more convenient than on a cron schedule.
What do you think @YeagerAI-Bulat @AgustinRamiroDiaz

**Comment by cristiam86** [comment]
@YeagerAI-Bulat please add an issue for this one and adapt the branch name and the PR title

**Comment by AgustinRamiroDiaz** [comment]
> I think that running this workflow on PR open and on every or update could be more convenient than on a cron schedule. What do you think @YeagerAI-Bulat @AgustinRamiroDiaz

I agree, since it will help us see diffs in each PR

**Comment by AgustinRamiroDiaz** [comment]
@YeagerAI-Bulat where will we see the reports on PRs?

**Comment by YeagerAI-Bulat** [comment]
@AgustinRamiroDiaz We need to merge it first, then you can check it here:
https://github.com/yeagerai/genlayer-simulator/security/code-scanning/tools/CodeQL/status/configurations/automatic

**Comment by YeagerAI-Bulat** [comment]
@cristiam86 [Issue #337](https://github.com/yeagerai/genlayer-simulator/issues/337) has been created and linked to this PR

**Comment by YeagerAI-Bulat** [comment]
@cristiam86 @AgustinRamiroDiaz 
Please review this PR

**Review by AgustinRamiroDiaz — APPROVED** [review]

**Pull request merged**
